name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test || echo "No hay tests aún"

      - name: Montar en Render
        run: |
          curl -X POST ${{secrets.RENDER_DEPLOY_HOOK}}
